import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from "@/wrapper/ScrollWrapper";
import { inter, orpix } from "@/fonts";
import Navbar from "@/components/Navigation/Navbar";
import FluidCursorOverlay from "@/components/Reusable/FluidCursor";



export const metadata: Metadata = {
  title: "Verq",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${orpix.variable} antialiased`}
      >
        <LenisProvider>
          <FluidCursorOverlay />
          <Navbar />
          {children}
         
        </LenisProvider>

      </body>
    </html>
  );
}
